---
- name: "copy files and unpack"
  become: yes
  unarchive:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu
    remote_src: no
    mode: 0755

- name: Install backend
  npm:
    path: /home/ubuntu

- name: start backend
  become: yes
  shell: |
    pm2 stop default
    pm2 start npm -- start